[env]
TERM = "xterm-256color"

[window]
decorations = "full"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 10
y = 10

[font]
size = 12.0

[font.normal]
family = "Fira Code"
style = "Regular"

[colors.primary]
background = "#241B30"
foreground = "#F2F2E3"

[colors.normal]
black = "#241B30"
red = "#9A0048"
green = "#00986C"
yellow = "#ADAD3E"
blue = "#6E29AD"
magenta = "#B300AD"
cyan = "#00B0B1"
white = "#B9B1BC"

[colors.bright]
black = "#7F7094"
red = "#E60A70"
green = "#0AE4A4"
yellow = "#F9F972"
blue = "#AA54F9"
magenta = "#FF00F6"
cyan = "#00FBFD"
white = "#F2F2E3"

[cursor.style]
shape = "beam"
blinking = "On"

[scrolling]
history = 40000

[mouse]
hide_when_typing = true
